Repository COSC481W-2025Winter/SurvivalChess, pull requests merged in 2025-03, with the labels that each got.

#38 Ritu/settingsmenue
  package-lock.json
  src/game/scenes/Game.js
  src/game/scenes/Settings.test.js
  src/game/scenes/SettingsButton.js
  src/game/scenes/Start.js
  src/game/scenes/settings.js
Labels: enhancement, sprint-1

#67 align chessboard & add non-dynamic sideLights
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game-objects/test/chessboard.test.js
Labels: enhancement, sprint-2

#70 add king royal & coordinate tracking & fix indent
  src/game-objects/board-state.js
  src/game-objects/chess-piece.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game-objects/piece-coordinates.js
  src/game-objects/pieces-taken.js
  src/game-objects/test/chessboard.test.js
  src/game/scenes/Game.js
  src/game/scenes/Promotion.js
Labels: enhancement, sprint-2

#77 Riana - Modified Rules Scene
  src/game-objects/constants.js
  src/game/scenes/RulesOverlay.js
  src/game/scenes/RulesOverlay.test.js
Labels: enhancement

#79 David/dev mode
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game-objects/dev-buttons.js
  src/game-objects/test/chessboard.test.js
Labels: enhancement, sprint-2

#82 Stat Tracking & Game End upon Checkmate & Stalemate
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game-objects/global-stats.js
  src/game-objects/test/chessboard.test.js
  src/game/scenes/GameOver.js
  src/game/scenes/GameOver.test.js
Labels: enhancement, sprint-2

#87 Riana - Made game over scene match aesthetic
  eslint.config.js
  src/game-objects/constants.js
  src/game/scenes/Game.js
  src/game/scenes/GameOver.js
Labels: enhancement

#91 fix king's non-un-highlight when other piece moves
  src/game-objects/chess-tiles.js
Labels: bug, sprint-2

#93 add elaborate testing for stat tracking & game end
  src/game-objects/board-state.js
  src/game-objects/test/chessboard.test.js
Labels: documentation, sprint-2

#96 Add dev button that toggles AI
  src/game-objects/chess-tiles.js
  src/game-objects/dev-buttons.js
  src/game-objects/test/chessboard.test.js
Labels: enhancement, sprint-2

#97 fixed issue with gameOver screen not having game as background
  src/game-objects/chess-tiles.js
  src/game-objects/test/chessboard.test.js
Labels: bug, sprint-2
