Repository COSC481W-2025Winter/SurvivalChess, pull requests merged in 2025-04, with the labels that each got.

#119 Resize Texts & Images when the Window Dimension changes
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game-objects/dev-buttons.js
  src/game-objects/pieces-taken.js
  src/game-objects/test/chessboard.test.js
  src/game/scenes/Game.js
  src/game/scenes/GameOver.js
  src/game/scenes/Promotion.js
  src/game/scenes/Rules.js
  src/game/scenes/Start.js
Labels: sprint 3

#127 Add comments & rudimentary testing for resizing
  src/game-objects/constants.js
  src/game-objects/test/chessboard.test.js
Labels: documentation

#121 Marley/ai - AI Improvement
  package-lock.json
  src/game-objects/board-mockups.js
  src/game-objects/board-state.js
  src/game-objects/chess-piece.js
  src/game-objects/chess-tiles.js
  src/game-objects/computer-logic.js
  src/game-objects/constants.js
  src/game-objects/piece-coordinates.js
  src/game-objects/test/computer-logic.test.js
  src/game/scenes/GameOver.js
  src/game/scenes/GameOver.test.js
Labels: enhancement, sprint 3

#135 Restore resize functionality of rules scene
  src/game/scenes/Rules.js
Labels: bug, sprint 3

#136 fix rules resizing again
  src/game/scenes/Rules.js
Labels: bug, sprint 3

#137 Durva/settings resize
  src/game/scenes/Settings.js
Labels: help wanted, sprint 3

#143 Remove duplicate devButtons & remove devButton
  src/game-objects/chess-tiles.js
  src/game-objects/dev-buttons.js
Labels: bug

#151 Marley/ai tweaks
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
  src/game-objects/computer-logic.js
  src/game-objects/test/computer-logic.test.js
Labels: bug, sprint 3

#146 Riana - Change rectangle cover to destroy buttons
  src/game-objects/chess-tiles.js
  src/game/scenes/Game.js
  src/game/scenes/GameOver.js
Labels: bug, sprint 3

#152 ABC - always be capturing
  src/game-objects/computer-logic.js
Labels: bug, enhancement, sprint 3
