Repository COSC481W-2025Winter/SurvivalChess, pull requests merged in 2025-02, with the labels that each got.

#30 Add foundational chess board & pieces & rules to build upon
  public/assets/drummyfish chess/bishopB.png
  public/assets/drummyfish chess/bishopB2.png
  public/assets/drummyfish chess/bishopB3.png
  public/assets/drummyfish chess/bishopW.png
  public/assets/drummyfish chess/bishopW2.png
  public/assets/drummyfish chess/bishopW3.png
  public/assets/drummyfish chess/board.png
  public/assets/drummyfish chess/icon.png
  public/assets/drummyfish chess/kingB.png
  public/assets/drummyfish chess/kingB2.png
  public/assets/drummyfish chess/kingB3.png
  public/assets/drummyfish chess/kingW.png
  public/assets/drummyfish chess/kingW2.png
  public/assets/drummyfish chess/kingW3.png
  public/assets/drummyfish chess/knightB.png
  public/assets/drummyfish chess/knightB2.png
  public/assets/drummyfish chess/knightB3.png
  public/assets/drummyfish chess/knightW.png
  public/assets/drummyfish chess/knightW2.png
  public/assets/drummyfish chess/knightW3.png
  public/assets/drummyfish chess/pawnB.png
  public/assets/drummyfish chess/pawnB2.png
  public/assets/drummyfish chess/pawnB3.png
  public/assets/drummyfish chess/pawnW.png
  public/assets/drummyfish chess/pawnW2.png
  public/assets/drummyfish chess/pawnW3.png
  public/assets/drummyfish chess/queenB.png
  public/assets/drummyfish chess/queenB2.png
  public/assets/drummyfish chess/queenB3.png
  public/assets/drummyfish chess/queenW.png
  public/assets/drummyfish chess/queenW2.png
  public/assets/drummyfish chess/queenW3.png
  public/assets/drummyfish chess/rookB.png
  public/assets/drummyfish chess/rookB2.png
  public/assets/drummyfish chess/rookB3.png
  public/assets/drummyfish chess/rookW.png
  public/assets/drummyfish chess/rookW2.png
  public/assets/drummyfish chess/rookW3.png
  public/assets/drummyfish chess/squareB.png
  public/assets/drummyfish chess/squareW.png
  src/game-objects/board-state.js
  src/game-objects/chess-piece.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game/scenes/Game.js
Labels: enhancement, sprint-1

#31 En-Passant Bug Fix
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
Labels: bug

#35 Add Threat Detection & Highlight of Threats on Board
  src/game-objects/board-state.js
  src/game-objects/chess-piece.js
  src/game-objects/chess-tiles.js
  src/game-objects/constants.js
  src/game/main.js
  src/game/scenes/Game.js
Labels: enhancement, sprint-1

#42 Made the Start Scene more aesthetic
  index.html
  package-lock.json
  src/game-objects/constants.js
  src/game/main.js
  src/game/scenes/Start.js
Labels: documentation, enhancement, sprint-1

#43 Implement Castling & Add Game-Objects Testing Framework
  src/game-objects/board-state.js
  src/game-objects/chess-piece.js
  src/game-objects/chess-tiles.js
  src/game-objects/test/chess-tiles.test.js
  src/game-objects/test/test-constants.js
Labels: bug, enhancement, sprint-1

#47 Pawn Promotion
  src/game-objects/chess-tiles.js
  src/game/scenes/Game.js
  src/game/scenes/Promotion.js
  src/game/scenes/Promotion.test.js
Labels: enhancement, sprint-1

#52 debugging for pawn capture and en passant
  src/game-objects/chess-tiles.js
  src/game-objects/pieces-taken.js
Labels: bug, sprint-1

#53 Add Testing for the Game Objects
  src/game-objects/board-state.js
  src/game-objects/chess-tiles.js
  src/game-objects/test/chess-tiles.test.js
  src/game-objects/test/chessboard.test.js
Labels: bug, sprint-1
